export component AppWindow inherits Window {
    // Di Wasm, Window akan otomatis memenuhi canvas pembungkusnya
    background: transparent;
    
    callback take_photo();

    // Area interaksi
    Rectangle {
        width: 100%;
        height: 100%;

        // Tombol Shutter
        Rectangle {
            width: 80px;
            height: 80px;
            background: white;
            border-radius: 40px;
            y: parent.height - 100px;
            border-width: 4px;
            border-color: #cccccc;

            touch := TouchArea {
                clicked => { root.take_photo(); }
            }
            
            // Efek visual saat ditekan
            states [
                pressed when touch.pressed : {
                    background: #aaaaaa;
                }
            ]
        }
    }
}
