import { Button } from "std-widgets.slint";

export component AppWindow inherits Window {
    background: transparent;
    callback take_photo();

    Rectangle {
        width: 100%;
        height: 100%;

        // Tombol Shutter Putih
        shutter := Rectangle {
            width: 70px;
            height: 70px;
            background: white;
            border-radius: 35px;
            y: parent.height - 80px;
            border-width: 5px;
            border-color: rgba(255, 255, 255, 0.4);

            touch := TouchArea {
                clicked => { root.take_photo(); }
            }

            // Animasi kecil saat ditekan
            states [
                active when touch.pressed : {
                    background: #dddddd;
                    width: 65px;
                    height: 65px;
                }
            ]
        }
    }
}
