import { Button } from "std-widgets.slint";

export component AppWindow inherits Window {
    width: 100%;
    height: 100%;
    background: transparent;
    
    callback take_photo();

    Rectangle {
        // Lingkaran Shutter di tengah bawah
        TouchArea {
            width: 70px;
            height: 70px;
            y: parent.height - 100px;
            clicked => { root.take_photo(); }
            
            Rectangle {
                border-radius: 35px;
                background: white;
                border-width: 5px;
                border-color: rgba(255, 255, 255, 0.3);
                
                Text {
                    text: "REC";
                    color: red;
                    font-size: 12px;
                    font-weight: 900;
                }
            }
        }
    }
}
