name: Deploy Tiny Wasm
on:
  push:
    branches: [ main ]
permissions:
  contents: write
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        run: rustup target add wasm32-unknown-unknown
      - name: Build
        run: cargo build --release --target wasm32-unknown-unknown
      - name: Optimize
        run: |
          sudo apt-get update && sudo apt-get install -y binaryen
          wasm-opt -Oz target/wasm32-unknown-unknown/release/wasm_tiny.wasm -o tiny.wasm
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          publish_files: index.html,tiny.wasm
